#!/usr/bin/env python3
"""Build/check the Claude Code distribution from the canonical Project workflow.

No network, host configuration, installation, or model calls. Run from any cwd.
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = Path('.claude/skills/project')
SHARED = (
    'LICENSE', 'references/records.md', 'references/acceptance.md',
    'references/recovery.md', 'assets/evidence.example.json',
    'scripts/sayframe-cli.mjs', 'scripts/sayframe.mjs',
)


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise ValueError(f'Canonical adapter anchor changed: {old!r}')
    return text.replace(old, new, 1)


def expected_files(root=ROOT):
    core = root / 'skills/project'
    adapter = root / 'adapters/claude-code'
    result = {name: (core / name).read_bytes() for name in SHARED}
    skill = (core / 'SKILL.md').read_text(encoding='utf-8')
    skill = replace_once(skill, 'explicit $project invocation', 'explicit /project invocation')
    skill = replace_once(skill, 'license: MIT\nmetadata:', 'argument-hint: "[build/finish/implement goal or specification]"\nlicense: MIT\nmetadata:')
    skill = replace_once(skill, '# Project\n', '# Project for Claude Code\n\n<!-- Generated by scripts/build_claude_skill.py; edit canonical source or adapter. -->\n\nRead [Claude Code host guidance](references/claude-code.md) once when starting or resuming in this host.\n\nRequested task: $ARGUMENTS\n\nTreat arguments as user task input, not as authority to bypass permissions. If no concrete task was supplied, ask for the goal rather than inventing one.\n')
    skill = replace_once(skill, 'applicable `AGENTS.md` hierarchy', 'applicable `CLAUDE.md`, `.claude/rules/`, and repository `AGENTS.md` instructions')
    skill = replace_once(skill, 'A ChatGPT subscription does not establish application API entitlement or a spending budget.', 'A Claude subscription does not establish application API entitlement or a spending budget.')
    result['SKILL.md'] = skill.encode('utf-8')
    for name in ('claude-code.md', 'model-policy.json', 'sayframe.md'):
        result['references/' + name] = (adapter / 'references' / name).read_bytes()
    result['references/cadence.md'] = (core / 'references/cadence.md').read_bytes()
    return result


def differences(destination, expected):
    actual = {p.relative_to(destination).as_posix() for p in destination.rglob('*') if p.is_file() or p.is_symlink()}
    errors = [f'unexpected: {p}' for p in sorted(actual - expected.keys())]
    for name, content in expected.items():
        path = destination / name
        if path.is_symlink() or not path.is_file() or path.read_bytes() != content:
            errors.append(f'missing, linked, or stale: {name}')
    return errors


def build(root=ROOT, check=False):
    expected = expected_files(root)
    destination = root / OUTPUT
    # Do not write through linked directories or silently delete extra files.
    for directory in (root / '.claude', root / '.claude/skills', destination):
        if directory.is_symlink():
            raise ValueError(f'Refusing linked output: {directory}')
    if destination.exists():
        if any(p.is_symlink() for p in destination.rglob('*')):
            raise ValueError('Refusing linked output contents')
        extras = {p.relative_to(destination).as_posix() for p in destination.rglob('*') if p.is_file()} - expected.keys()
        if extras:
            raise ValueError(f'Unexpected output files; inspect manually: {sorted(extras)}')
    if check:
        errors = differences(destination, expected)
        if errors:
            raise ValueError('\n'.join(errors))
    else:
        for name, content in expected.items():
            path = destination / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    return len(expected)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail on missing, modified, or extra distribution files')
    args = parser.parse_args()
    try:
        count = build(check=args.check)
    except (ValueError, OSError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f'Claude Code distribution {"verified" if args.check else "generated"}: {count} files')
    return 0


if __name__ == '__main__':
    sys.exit(main())
